name: Unit tests && integration tests

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        node: [ 16, 18, 20 ]
    steps:
      - uses: actions/checkout@v4
        id: git-clone
        name: Cloning repository

      - uses: pnpm/action-setup@v4
        id: install-pnpm
        name: Installing PNPM
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v4
        id: set-nodejs
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install dependencies
        id: set-deps
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        id: unit-tests
        run: pnpm run test
